### ISSUE TITLE
Example values for jwt generation

### ISSUE THREAD

**Issue by 0xjams** [admin-ch/CovidCode-Service#10]
Could  you provide example values in the README.md file for these parameters?

    @Value("${authcodegeneration.jwt.token-validity}")
    private long tokenValidity;

    @Value("${authcodegeneration.jwt.issuer}")
    private String issuer;

    @Value("${authcodegeneration.jwt.privateKey}")
    private String privateKey;

    @Value("${authcodegeneration.service.keycloak.realm}")
    private String realm;

    @Value("${authcodegeneration.service.keycloak.uri}")
    private String serviceUrl;

    @Value("${authcodegeneration.service.keycloak.masterPassword}")
    private String masterPassword;

    @Value("${authcodegeneration.service.keycloak.clientSecret}")
    private String clientSecret;

    authcodegeneration.jwt.token-validity = 65535
    authcodegeneration.jwt.issuer = ""
    authcodegeneration.jwt.privateKey = ""
    authcodegeneration.service.keycloak.realm=""
    authcodegeneration.service.keycloak.uri=""
    authcodegeneration.service.keycloak.masterPassword=""
    authcodegeneration.service.keycloak.clientSecret=""
    authcodegeneration.monitor.prometheus.user=""
    authcodegeneration.monitor.prometheus.password=""
    ha-authcode-generation-service.allowed-origin="*"

**Comment by fabe2913** [comment]
Thanks for your comment. 
We added today more information in the README.md file.

**Comment by fabe2913** [comment]
We added today more information in the README.md file for the JWT.
